### PR TITLE
Added full Spanish (es_es) language support [FINISHED]

### PR DESCRIPTION
**Pull request by FrannDzs**
@TwistedGate @Flaxbeard Hello, how are you? I hope you are well. I've been translating some mods, like Immersive Engineering and I also translated Immersive Petroleum completely to spanish language, I'll continue with Immersive Railroading :p.
When you have time, merge the changes. Greetings!

### CODE REVIEW

**Comment by FrannDzs** [comment]
Added full support to the manual for Spanish language (es_es)

**Comment by TwistedGate** [comment]
Would you kindly move that over to 1.16.5? I moved things over to my repo https://github.com/TwistedGate/ImmersivePetroleum

**Comment by FrannDzs** [comment]
> Would you kindly move that over to 1.16.5? I moved things over to my repo https://github.com/TwistedGate/ImmersivePetroleum

I haven't been on GitHub for a while, sorry, do you know a quick way to move this to another branch? I haven't mastered this 100% :(. Regards!

**Comment by TwistedGate** [comment]
As far as i know you can't copy over PR's~
you'll have to fork my repo and copy over the files you've created/changed in there and then make a PR

**Pull request closed without merging**
